name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t murilobarceloss/multi-docker -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true murilobarceloss/multi-docker npm test

      - run: docker build -t murilobarceloss/multi-client ./client
      - run: docker build -t murilobarceloss/multi-nginx ./nginx
      - run: docker build -t murilobarceloss/multi-server ./server
      - run: docker build -t murilobarceloss/multi-worker ./worker

      - run: docker push murilobarceloss/multi-client
      - run: docker push murilobarceloss/multi-nginx
      - run: docker push murilobarceloss/multi-server
      - run: docker push murilobarceloss/multi-worker
